dist: trusty
language: java

env:
    global:
        - GRADLE_VERSION='5.0'
        - GRADLE_DISTRIBUTION_URL="https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip"
        - TERM=dumb
jdk:
    - oraclejdk8
    - openjdk8
before_install:
    - ( cd $HOME && curl -LO "https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip" )
    - ( cd $HOME && unzip -q gradle-$GRADLE_VERSION-bin.zip && rm gradle-$GRADLE_VERSION-bin.zip )
    - export PATH=$HOME/gradle-$GRADLE_VERSION/bin:$PATH && hash -r && gradle --version
script:
    - gradle build

notifications:
    email: false
